export const fileStructure=[
     {
        id:1,
        isFolder:true,
        fName:"node_modules",
        showChild:true,
        children:[{
            id:11,
            isFolder:true,
            fName:"bin",
            showChild:false,
            children:[
                {
                    id:111,
                    isFolder:false,
                    fName:"deletedItems",
                    children:[]
                },
                {
                    id:112,
                    isFolder:false,
                    fName:"bin",
                    children:[]
                }
            ]
        }]
     },
     {
        id:2,
        isFolder:true,
        fName:"public",
        showChild:false,
        children:[
            {
                id:21,
                isFolder:true,
                fName:"bin",
                showChild:false,
                children:[
                    {
                        id:221,
                        isFolder:false,
                        fName:"bin",
                        children:[]
                        
                    },
                    {
                        id:222,
                        isFolder:false,
                        fName:"bin",
                        children:[]
                    }
                ]
            }
        ]
     },
     {
        id:3,
        isFolder:true,
        fName:"src",
        showChild:false,
        children:[
            {
               id:31,
               isFolder:false,
               fName:"bin",
               children:[]
           },
           {
               id:32,
               isFolder:false,
               fName:"bin",
               children:[]
           }
        ]
     },
     {
        id:4,
        isFolder:true,
        fName:"assets",
        showChild:false,
        children:[
            {
              id:41,
              isFolder:false,
              fName:"bin",
              children:[]
            },
            {
              id:42,
              isFolder:false,
              fName:"bin",
              children:[]
            },
            {
              id:43,
              isFolder:false,
              fName:"bin",
              children:[]
            }
        ]
     },
     {
        id:5,
        isFolder:true,
        fName:"assets",
        showChild:true,
        children:[
            {
              id:51,
              isFolder:false,
              fName:"bin",
              children:[]
            },
            {
              id:52,
              isFolder:false,
              fName:"bin",
              children:[]
            },
            {
              id:53,
              isFolder:true,
              fName:"bin",
              showChild:false,
              children:[
                {
                    id:53,
                    isFolder:true,
                    fName:"bin",
                    showChild:false,
                    children:[
                        {
                            id:53,
                            isFolder:true,
                            fName:"bin",
                            showChild:false,
                            children:[
                                {
                                    id:53,
                                    isFolder:true,
                                    fName:"bin",
                                    showChild:false,
                                    children:[
                                        {
                                            id:53,
                                            isFolder:true,
                                            fName:"bin",
                                            showChild:false,
                                            children:[
                                                {
                                                    id:53,
                                                    isFolder:true,
                                                    showChild:false,
                                                    fName:"bin",
                                                    children:[
                                                        {
                                                            id:53,
                                                            isFolder:true,
                                                            showChild:false,
                                                            fName:"bin",
                                                            children:[]
                                                          }
                                                    ]
                                                  }
                                            ]
                                          }
                                    ]
                                  }
                            ]
                          }
                    ]
                  }
              ]
            }
        ]
     },
     {
        id:6,
        isFolder:true,
        fName:"assets",
        showChild:false,
        children:[
            {
              id:61,
              isFolder:false,
              fName:"bin",
              children:[]
            },
            {
              id:62,
              isFolder:false,
              fName:"bin",
              children:[]
            },
            {
              id:63,
              isFolder:false,
              fName:"bin",
              children:[]
            }
        ]
     }
]


